[2024-11-18T10:52:10.538+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T10:52:10.635+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.extract_weather_data manual__2024-11-18T10:47:03.774988+00:00 [queued]>
[2024-11-18T10:52:10.677+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.extract_weather_data manual__2024-11-18T10:47:03.774988+00:00 [queued]>
[2024-11-18T10:52:10.677+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 6
[2024-11-18T10:52:10.718+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): extract_weather_data> on 2024-11-18 10:47:03.774988+00:00
[2024-11-18T10:52:10.741+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=484) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T10:52:10.744+0000] {standard_task_runner.py:72} INFO - Started process 485 to run task
[2024-11-18T10:52:10.742+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'extract_weather_data', 'manual__2024-11-18T10:47:03.774988+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmpbm3o85ty']
[2024-11-18T10:52:10.747+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask extract_weather_data
[2024-11-18T10:52:10.860+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_pipeline.extract_weather_data manual__2024-11-18T10:47:03.774988+00:00 [running]> on host 527ca48b98a5
[2024-11-18T10:52:11.278+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naphat' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T10:47:03.774988+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T10:47:03.774988+00:00'
[2024-11-18T10:52:11.285+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T10:52:11.328+0000] {base.py:84} INFO - Retrieving connection 'open_weather_api'
[2024-11-18T10:52:12.726+0000] {python.py:240} INFO - Done. Returned value was: {'coord': {'lon': 100.5167, 'lat': 13.75}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 303.2, 'feels_like': 305.3, 'temp_min': 303.09, 'temp_max': 304.09, 'pressure': 1008, 'humidity': 56, 'sea_level': 1008, 'grnd_level': 1007}, 'visibility': 10000, 'wind': {'speed': 1.9, 'deg': 26, 'gust': 3.05}, 'clouds': {'all': 84}, 'dt': 1731926590, 'sys': {'type': 1, 'id': 9235, 'country': 'TH', 'sunrise': 1731885555, 'sunset': 1731926837}, 'timezone': 25200, 'id': 1609350, 'name': 'Bangkok', 'cod': 200}
[2024-11-18T10:52:12.773+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T10:52:12.774+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=extract_weather_data, run_id=manual__2024-11-18T10:47:03.774988+00:00, execution_date=20241118T104703, start_date=20241118T105210, end_date=20241118T105212
[2024-11-18T10:52:12.832+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T10:52:12.859+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T10:52:12.862+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
