[2024-11-18T10:43:08.276+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T10:43:08.731+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.extract_weather_data manual__2024-11-18T10:42:58.809011+00:00 [queued]>
[2024-11-18T10:43:09.002+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.extract_weather_data manual__2024-11-18T10:42:58.809011+00:00 [queued]>
[2024-11-18T10:43:09.004+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-11-18T10:43:09.227+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): extract_weather_data> on 2024-11-18 10:42:58.809011+00:00
[2024-11-18T10:43:09.368+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=277) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T10:43:09.388+0000] {standard_task_runner.py:72} INFO - Started process 278 to run task
[2024-11-18T10:43:09.395+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'extract_weather_data', 'manual__2024-11-18T10:42:58.809011+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmprv0k4suc']
[2024-11-18T10:43:09.417+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask extract_weather_data
[2024-11-18T10:43:09.916+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_pipeline.extract_weather_data manual__2024-11-18T10:42:58.809011+00:00 [running]> on host 527ca48b98a5
[2024-11-18T10:43:11.152+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naphat' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T10:42:58.809011+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T10:42:58.809011+00:00'
[2024-11-18T10:43:11.158+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T10:43:11.176+0000] {logging_mixin.py:190} INFO - Calling API endpoint: https://api.openweathermap.org/data/2.5/weather?q=Bangkok&appid=cedf8b9a94cdddf7669893c445715532
[2024-11-18T10:43:11.176+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T10:43:11.213+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T10:43:11.215+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=extract_weather_data, run_id=manual__2024-11-18T10:42:58.809011+00:00, execution_date=20241118T104258, start_date=20241118T104308, end_date=20241118T104311
[2024-11-18T10:43:11.327+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T10:43:11.390+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T10:43:11.392+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
